version: 7
profiles:
  - type: ssh
    name: AIG-301
    icon: fas fa-desktop
    options:
      host: 192.168.1.17
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      auth: password
      user: moxa
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    terminalColorScheme:
      name: 3024 Night
      foreground: '#a5a2a2'
      background: '#090300'
      cursor: '#a5a2a2'
      colors:
        - '#090300'
        - '#db2d20'
        - '#01a252'
        - '#fded02'
        - '#01a0e4'
        - '#a16a94'
        - '#b5e4f4'
        - '#a5a2a2'
        - '#5c5855'
        - '#e8bbd0'
        - '#3a3432'
        - '#4a4543'
        - '#807d7c'
        - '#d6d5d4'
        - '#cdab53'
        - '#f7f7f7'
    group: 0d83f172-508c-4d86-96de-db43125265c3
    id: ssh:custom:AIG-301:8baf7c98-69c5-4297-9dec-f289d5527519
  - type: ssh
    name: UC2112
    icon: fas fa-desktop
    options:
      host: 192.168.1.128
      user: moxa
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    group: 0d83f172-508c-4d86-96de-db43125265c3
    id: ssh:custom:UC2112:193ce8cb-8215-4e72-bc68-46b5df395f6c
  - type: ssh
    name: GIA-E-LA
    icon: fas fa-desktop
    options:
      host: 80.251.208.251
      port: 28104
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      auth: password
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    id: ssh:custom:GIA-E-LA:0844acb4-6791-48b7-86e9-fbda075bd437
    group: 3bc6f780-70f2-498b-9329-d60a6c9150f0
  - type: ssh
    name: GIA-E-JP
    icon: fas fa-desktop
    options:
      host: 23.106.140.47
      port: 28139
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      auth: password
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    group: 3bc6f780-70f2-498b-9329-d60a6c9150f0
    id: ssh:custom:GIA-E-JP:cfcb98ae-ab84-4299-a1e9-8ab8b574e2af
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 20.18.13.13
      user: ems-vm02-admin
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      auth: password
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    name: VM02-CD
    group: 7aedf9af-d2c1-4010-b1cf-52dbca2ef427
    id: ssh:custom:VM02-CD:6f94d9c8-b511-4ef9-8ffb-c92f6b8bbc91
groups:
  - id: 0d83f172-508c-4d86-96de-db43125265c3
    name: MOXA
  - id: 3bc6f780-70f2-498b-9329-d60a6c9150f0
    name: VM-Personal
  - id: 7aedf9af-d2c1-4010-b1cf-52dbca2ef427
    name: VM-Work
configSync:
  parts: {}
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-line:
    - Ctrl-Shift-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - Alt-PageUp
  scroll-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - Ctrl-Shift-T
  new-window:
    - Ctrl-Shift-N
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-S
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  close-pane: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
terminal:
  searchOptions: {}
  colorScheme:
    name: Tabby Default
    foreground: '#cacaca'
    background: '#171717'
    cursor: '#bbbbbb'
    colors:
      - '#000000'
      - '#ff615a'
      - '#b1e969'
      - '#ebd99c'
      - '#5da9f6'
      - '#e86aff'
      - '#82fff7'
      - '#dedacf'
      - '#313131'
      - '#f58c80'
      - '#ddf88f'
      - '#eee5b2'
      - '#a5c7ff'
      - '#ddaaff'
      - '#b7fff9'
      - '#ffffff'
  profile: local:powershell-core
  customColorSchemes: []
  fontSize: 16
  font: Hack Nerd Font
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
  autoOpen: false
ssh:
  knownHosts:
    - host: 192.168.1.17
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 8JLVUVVz1Q/n06um8xRwzxNv3hq55jyQ4aWeoSpvzPg=
    - host: 192.168.1.128
      port: 22
      type: ecdsa-sha2-nistp256
      digest: ZnyIujhctm1sLwkKcRgWoruG9uurryUqyfu7RU7lK0g=
    - host: 80.251.208.251
      port: 28104
      type: ecdsa-sha2-nistp256
      digest: 9q95HYKcUz01+anjjLjbayeTd6nJUmS9vPGSHF0oSYw=
    - host: 23.106.140.47
      port: 28139
      type: ecdsa-sha2-nistp256
      digest: J441wlhGkSTxzTW/u8co+Z7pUHG+R4W6thzoF4ZE2kA=
    - host: 20.18.13.13
      port: 22
      type: ecdsa-sha2-nistp256
      digest: faSRNgON8cDw24uQ3KXfUxg3C2QgBdoyKDvNkWa8WSI=
clickableLinks: {}
accessibility: {}
appearance:
  opacity: 0.92
  vibrancyType: fluent
  vibrancy: true
hacks:
  disableVibrancyWhileDragging: true
  disableGPU: true
providerBlacklist: []
commandBlacklist: []
language: zh-CN
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist:
  - local:clink
  - local:cmd
  - local:powershell
  - local:default
vault:
  version: 1
  contents: >-
    HH5sf1d55lrPjx7Z6Rn9bK2d0+z9mI2NzGWV0Iz6CAcnunqOgZkL3gj0mnTHeKJbE9AgYtJugVpVtregjgx0R3HrylZDdYB1PJrzwPLnJD7xQd3ZH8rmO2JoXBwxIjD8cToM6Exx7qPwD+BRGrrJAKUqDNBu7EAlEJrrOBhGwaMHiwjmJ37eYV85a8uscxpMnVtiayxM96k5q0w65xNgHshphpenOBoyHqkJyVTolh1wZgbDatCYzjnUN8VR7qsKS3pHrhwCTg1Tdjtv4LcGckTcJ1hDJpjbvv33qekFvhazt7DFkyPoRLuTnqXDUlzeOD7oa3O4B1c28uF3W3Pzchpn2zcg2aHLwWRsFI5vbqJBlB854LPhEvP/dwCyRNeKmqT5TdDCvE/SAuEad5XWBbGtXjbuL+lA+ZYnpYVv3I6029AUpaxflagTJC19e334m8JPzmbCiZ9x30k/ECOqsRYHqsnlIw5hG9uRfjfLLA6Y60Vwpr0nPVZHNOUW0HOXJCAc4ANR9Tcs77EzbDdS8FBszDA9mAA1/FhJYUCSPXrW+Nwm1Dfs/pJbleSn7DuaFes3vmRhnaRwQ7qdkwrFgJukDzz95E6tiqF65ZKTNG9PyPSn30874uyT1DIb5/+pLc+PJsDh8qHwhZmmXbIiCBeAf3ZcOAhbNv6OsPJLqd9hEQ6G7C8Vh7HA/EFDNXkN
  keySalt: 1bcc9f5b8f250e30
  iv: 9506c2c81cb78470aa0dfdc5a351660c
